# Header
navbar_brand: false
menu:
  Home: index.html
  Archives: archives/
  Categories: categories/
  # Projects: projects/ 
  Moments: moments/
  Comments: comments/
  Links: links/
  About: about/
 
rss: /atom.xml

# Content
excerpt_link: Read more...
fancybox: true
wordcount: true
viewcount: true
timecost: false
language: zh-CN

# Sidebar
widgets:
- about         # See also: `about_content`
- recent_posts
- calendar
# - translate
- category
- archive
- search

#- tag
#- tagcloud
about_widget_content: >
  <a target="_blank" href="about">
  <img  id="avatar-logo" width=100%  alt="WizardLQ" src="http://www.gravatar.com/avatar/d14c7c7faf5e1f3001c070f3141d698f?s=512">
  </a>
  <p>Welcome to my magic blog, I am a 1st year master of Automation. <strong>"Science and technology is the magic of mortal"</strong>. 
  To know more about me, click <a href="/about">Here</a>
  </p>

# widget behavior
archive_type: 'monthly'
show_count: true

# Miscellaneous
google_analytics: # UA-122713769-1
favicon: images/icon.png
twitter_id:
google_plus: 112373242775367333102
fb_admins:
fb_app_id:
# baidu analytics
baidu_tongji: true

# https://github.com/hustcc/canvas-nest.js
canvas_nest: false

# https://github.com/imsun/gitment
# https://coding.net/  can be deployed to coding
# gitment: false
gitment:
  owner: liuqidev
  repo: liuqidev.github.io
  client_id: 5e40c2a3bf3076fce203
  client_secret: 58df99a3d1b4f78555bfa8ebddfefbce4b0524d8
  local_id: 60bcecf77b594c435fc5
  local_secret: b492c879473fdb14ca091697ffb0f03fab646c7f
  coding_owner: liuqidev
  coding_repo: liuqidev.coding.me
  coding_id: 1dc5be42b7acd0c2612856da6d5d4817   
  coding_secret: f908fdf66dbca953af36bf49775bb73a89aff4d6
 
# Valine Comment system. https://valine.js.org
valine: false
# valine:
  # enable: true # 如果你想使用valine，请将值设置为 true
  # appId: kBrTfD8l4RFzueSAt65hASek-gzGzoHsz # your leancloud appId
  # appKey: AFsAfwfHqW6iEHkAc3TjYEzh # your leancloud appKey
  # notify: false # Mail notify
  # verify: false # Verify code
  # avatar: mm # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  # placeholder: Say something~ # Comment Box placeholder
  # guest_info: nick,mail # Comment header info
  # pageSize: 20 # comment list page size

# livere https://livere.com/
livere: false
# livere:
  # dataUID: MTAyMC8zODU5MS8xNTExOQ==
 
# http://www.daovoice.io
dao_voice: false
# dao_voice:
  # appId: a2c8df52
  
eyes_protected: false

# dynamic_title
title_change: false
# title_change:
  # normal: o(∩_∩)o Welcome!
  # leave: Opoos...●﹏●

mathjax: true

# http://howiefh.github.io/2016/04/29/hexo-s-calendar-plugin/?utm_source=tuicool
calendar:
  language: en 
  options:
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
    dayOfWeekShort: ['S', 'M', 'T', 'W', 'T', 'F', 'S']
    dayOfWeek: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday']
    postsMonthTip: 'Posts published in LMM yyyy'
    titleFormat: 'yyyy LMM'
    titleLinkFormat: '/archives/yyyy/MM/'
    headArrows: {previous: '<span class="cal-prev"></span>', next: '<span class="cal-next"></span>'}
    footArrows: {previous: ' ', next: ' '}
    weekOffset: 0
    single: false
    root: '/calendar/'
    url: '/calendar.json'

<<<<<<< HEAD
theme: jekyll-theme-architect
show_downloads: true
=======
theme: jekyll-theme-cayman
>>>>>>> f6f86ee060c67332aa53b3554a76d4bea5d93c70
